spring.application.name=patitas
spring.datasource.url=jdbc:postgresql://localhost:5432/BasePatitas
spring.datasource.username=postgres
spring.datasource.password=Lamitadmas12#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    
server.address=0.0.0.0
server.port=8080

jwt.secret=JedsR0sSeCod@wnsaAJedklsGodkaIO123456789012345
jwt.expiration=604800000
jwt.expirationRestored=600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patitasuaves.peluqueriacanina@gmail.com
spring.mail.password=nclc uqjv qrqw piwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

    app.upload.dir=D:/Main/Trabajos/ToDo/ProyectoPatitas/NewPatas/ImagenesPeluqueria