spring.datasource.url=jdbc:postgresql://dpg-d85o13rtqb8s73bsm3s0-a.oregon-postgres.render.com:5432/patitas_kq62
spring.datasource.username=patitas_kq62_user
spring.datasource.password=l9ryPGrPtSbqsct9JHMwHsQvi8RZbJWa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=JedsR0sSeCod@wnsaAJedklsGodkaIO123456789012345
jwt.expiration=604800000
jwt.expirationRestored=600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=patitasuaves.peluqueriacanina@gmail.com
spring.mail.password=nclc uqjv qrqw piwv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

